# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.

    -   id: end-of-file-fixer
        name: End of file fixer
        description: Fixes the ends of files for consistency.

    -   id: check-yaml
        name: Check yaml files
        description: Makes sure yaml files are formatted correctly.

    -   id: check-added-large-files
        name: Check large files
        description: Make sure giant files aren't checked in

    -   id: no-commit-to-branch
        name: Protect main branch
        description: Makes sure commits are blocked to the main branch.
