export default function LuminousMysteries() {
    return (
        <div>
            <h2>Baptism in the Jordan</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit ab commodi obcaecati, omnis dicta maxime dolorum magni asperiores recusandae architecto quis tempora voluptates quos doloremque mollitia dolor non quasi autem molestias at ipsa nostrum ipsam? Eligendi, accusantium sequi inventore excepturi temporibus molestiae rem dolorum, sunt corrupti nobis ab voluptate pariatur deserunt a quisquam deleniti tempore? Beatae exercitationem voluptatum nulla quaerat minus neque architecto quae sapiente rem autem, omnis laudantium, quibusdam reprehenderit tempora voluptatibus pariatur nostrum at eligendi tenetur labore. Sit accusamus ab dolor neque sequi porro, voluptates suscipit explicabo necessitatibus atque. Veritatis veniam necessitatibus, pariatur fuga voluptatum in recusandae numquam! Ipsam consequatur facilis accusamus molestias maxime earum commodi, exercitationem eum porro aut optio consequuntur at quibusdam magnam placeat officia expedita? Ad accusantium autem id velit ut itaque a sequi, doloribus animi laborum, necessitatibus enim architecto, accusamus rem consequuntur numquam corporis obcaecati natus perspiciatis amet at eum libero. Corporis, ut reiciendis.
            </p>

            <h2>The Wedding Feast at Cana</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit ab commodi obcaecati, omnis dicta maxime dolorum magni asperiores recusandae architecto quis tempora voluptates quos doloremque mollitia dolor non quasi autem molestias at ipsa nostrum ipsam? Eligendi, accusantium sequi inventore excepturi temporibus molestiae rem dolorum, sunt corrupti nobis ab voluptate pariatur deserunt a quisquam deleniti tempore? Beatae exercitationem voluptatum nulla quaerat minus neque architecto quae sapiente rem autem, omnis laudantium, quibusdam reprehenderit tempora voluptatibus pariatur nostrum at eligendi tenetur labore. Sit accusamus ab dolor neque sequi porro, voluptates suscipit explicabo necessitatibus atque. Veritatis veniam necessitatibus, pariatur fuga voluptatum in recusandae numquam! Ipsam consequatur facilis accusamus molestias maxime earum commodi, exercitationem eum porro aut optio consequuntur at quibusdam magnam placeat officia expedita? Ad accusantium autem id velit ut itaque a sequi, doloribus animi laborum, necessitatibus enim architecto, accusamus rem consequuntur numquam corporis obcaecati natus perspiciatis amet at eum libero. Corporis, ut reiciendis.
            </p>

            <h2>Proclamation of the Kingdom of God</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit ab commodi obcaecati, omnis dicta maxime dolorum magni asperiores recusandae architecto quis tempora voluptates quos doloremque mollitia dolor non quasi autem molestias at ipsa nostrum ipsam? Eligendi, accusantium sequi inventore excepturi temporibus molestiae rem dolorum, sunt corrupti nobis ab voluptate pariatur deserunt a quisquam deleniti tempore? Beatae exercitationem voluptatum nulla quaerat minus neque architecto quae sapiente rem autem, omnis laudantium, quibusdam reprehenderit tempora voluptatibus pariatur nostrum at eligendi tenetur labore. Sit accusamus ab dolor neque sequi porro, voluptates suscipit explicabo necessitatibus atque. Veritatis veniam necessitatibus, pariatur fuga voluptatum in recusandae numquam! Ipsam consequatur facilis accusamus molestias maxime earum commodi, exercitationem eum porro aut optio consequuntur at quibusdam magnam placeat officia expedita? Ad accusantium autem id velit ut itaque a sequi, doloribus animi laborum, necessitatibus enim architecto, accusamus rem consequuntur numquam corporis obcaecati natus perspiciatis amet at eum libero. Corporis, ut reiciendis.
            </p>

            <h2>Transfiguration</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit ab commodi obcaecati, omnis dicta maxime dolorum magni asperiores recusandae architecto quis tempora voluptates quos doloremque mollitia dolor non quasi autem molestias at ipsa nostrum ipsam? Eligendi, accusantium sequi inventore excepturi temporibus molestiae rem dolorum, sunt corrupti nobis ab voluptate pariatur deserunt a quisquam deleniti tempore? Beatae exercitationem voluptatum nulla quaerat minus neque architecto quae sapiente rem autem, omnis laudantium, quibusdam reprehenderit tempora voluptatibus pariatur nostrum at eligendi tenetur labore. Sit accusamus ab dolor neque sequi porro, voluptates suscipit explicabo necessitatibus atque. Veritatis veniam necessitatibus, pariatur fuga voluptatum in recusandae numquam! Ipsam consequatur facilis accusamus molestias maxime earum commodi, exercitationem eum porro aut optio consequuntur at quibusdam magnam placeat officia expedita? Ad accusantium autem id velit ut itaque a sequi, doloribus animi laborum, necessitatibus enim architecto, accusamus rem consequuntur numquam corporis obcaecati natus perspiciatis amet at eum libero. Corporis, ut reiciendis.
            </p>

            <h2>Institution of the Eucharist</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit ab commodi obcaecati, omnis dicta maxime dolorum magni asperiores recusandae architecto quis tempora voluptates quos doloremque mollitia dolor non quasi autem molestias at ipsa nostrum ipsam? Eligendi, accusantium sequi inventore excepturi temporibus molestiae rem dolorum, sunt corrupti nobis ab voluptate pariatur deserunt a quisquam deleniti tempore? Beatae exercitationem voluptatum nulla quaerat minus neque architecto quae sapiente rem autem, omnis laudantium, quibusdam reprehenderit tempora voluptatibus pariatur nostrum at eligendi tenetur labore. Sit accusamus ab dolor neque sequi porro, voluptates suscipit explicabo necessitatibus atque. Veritatis veniam necessitatibus, pariatur fuga voluptatum in recusandae numquam! Ipsam consequatur facilis accusamus molestias maxime earum commodi, exercitationem eum porro aut optio consequuntur at quibusdam magnam placeat officia expedita? Ad accusantium autem id velit ut itaque a sequi, doloribus animi laborum, necessitatibus enim architecto, accusamus rem consequuntur numquam corporis obcaecati natus perspiciatis amet at eum libero. Corporis, ut reiciendis.
            </p>
        </div>
    );
}